name: Build and Test DynamoRIO Client

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc g++ make

    - name: Download DynamoRIO
      run: |
        wget https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-10.93.19944/DynamoRIO-Linux-10.93.19944.tar.gz
        tar -xzf DynamoRIO-Linux-10.93.19944.tar.gz
        export DYNAMORIO_HOME=$PWD/DynamoRIO-Linux-10.93.19944
        export PATH=$PATH:$DYNAMORIO_HOME/bin64
    - name: Compile Target Program
      run: |
        gcc -o simple_target simple_client.c -I$DYNAMORIO_HOME/include -L$DYNAMORIO_HOME/lib64 -ldynamorio

    - name: Set executable permissions
      run: |
        chmod +x ./simple_target

    - name: Run Client
      run: |
        ./DynamoRIO-Linux-10.93.19944/bin64/drrun -- ./simple_target

